package com.subhadeep.protobuf;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.util.JsonFormat;
import example.simple.Simple.SimpleMessage;

public class ProtoToJSONMain {
    public static void main(String[] args) throws InvalidProtocolBufferException {
        // This builder will allow us to create simple messages directly from the code
        SimpleMessage.Builder builder = SimpleMessage.newBuilder();

        // setting the field values of the simple class that was generated by simple message in simple.proto file
        builder.setId(42);
        builder.setIsSimple(true);
        builder.setName("My Simple message name");

        /* One Thing that you can do with builder is that
         *  since, the set methods itself returns Builder
         * therefore you can set the values in the following way*/
        builder.setId(23)
                .setIsSimple(false)
                .setName("Message got changed, bitch!");

        /*Repeated fields of the Simple Class*/
        builder.addSampleList(1)
                .addSampleList(2)
                .addSampleList(3);

        // Print this as a JSON
        String jsonString = JsonFormat.printer()
//                .includingDefaultValueFields() - options
                .print(builder);
        System.out.println(jsonString);

        // get back proto files from JSON string
        SimpleMessage.Builder builder2 = SimpleMessage.newBuilder();

        JsonFormat.parser().ignoringUnknownFields()
                .merge(jsonString, builder2);
        System.out.println(builder2);
    }
}
